name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  SPM:
    name: "Tests via SPM"
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: set -o pipefail && swift test

  Carthage:
    name: "Test Carthage compatibility"
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cache Carthage
        id: cache-carthage
        uses: actions/cache@v1.1.0
        with:
          path: Carthage
          key: ${{ runner.os }}-cache-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: ${{ runner.os }}-cache-

      - name: Update Carthage
        if: steps.cache-carthage.outputs.cache-hit != 'true'
        run: |
          cd RxTimelane
          carthage bootstrap
          carthage build --no-skip-current

