name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  SPM:
    name: "Tests via SPM"
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: set -o pipefail && swift test

  Carthage:
    name: "Test Carthage compatibility"
    runs-on: macOS-latest

    steps:
    - uses: actions/cache@v1
      with:
        path: RxTimelane/Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
        restore-keys: |
          ${{ runner.os }}-carthage-
      
    - uses: actions/checkout@v2
    - name: Check Carthage build
      run: |
        cd RxTimelane
        carthage build --cache-builds

